gpu: -1
chunk_size: 100
batch_size: 1
num_workers: 0

# 
max_particles: 4

model:
  config_path_mv : saved_checkpoints/multipart/config_mv.yml
  config_path_t  : saved_checkpoints/multipart/config_t.yml
  checkpoint_path: saved_checkpoints/multipart/checkpoints/epoch=57-val/loss=3.5826.ckpt
  
  n_steps: 25
  n_steps_to_store: -1 # 5


inf_dict:
  info: "train dataset"

  n_ensemble: 10
  store_ensemble_components: false
  store_energy_incidence: true

  entry_stop_final: 250000 # 2500 jobs => 100*2500 = 250000

  truth_path: path_to_multipart_data/train.root
  dir_flag: train_n_steps_25_e_inc


  info: "val dataset"

  n_ensemble: 10
  store_ensemble_components: false
  store_energy_incidence: true

  entry_stop_final: 10000 # 100 jobs => 100*100 = 10000

  truth_path: path_to_multipart_data/val.root
  dir_flag: val_n_steps_25_e_inc


  info: "test dataset"

  n_ensemble: 10
  store_ensemble_components: false
  store_energy_incidence: true

  entry_stop_final: 50000 # 500 jobs => 100*500 = 50000

  truth_path: path_to_multipart_data/test.root
  dir_flag: test_n_steps_25_e_inc
