dataset: single_e

gpu: 1
chunk_size: 100
batch_size: 500
num_workers: 2


model:
  config_path_mv : saved_checkpoints/single_e/config_mv.yml
  config_path_t  : saved_checkpoints/single_e/config_t.yml
  checkpoint_path: saved_checkpoints/single_e/checkpoints/epoch=77-val/loss=3.8828.ckpt

  n_steps: 25
  n_steps_to_store: 5

items:
  - info: "test dataset"
    run_pred: true
    run_plot: true
    n_ensemble: 10
    save_ensemble_components: true

    truth_path: path_to_single_e_data/test.root
    pred_path: null

    dir_flag: n_steps_25
    entry_start: 0
    n_events: 10000

    plots:
      scatter: {}
      leading_jet_res: {pt_xrange: [-30, 30], eta_xrange: [-0.15, 0.15], phi_xrange: [-0.15, 0.15]}
