gpu: -1
chunk_size: 100
batch_size: 20
num_workers: 0


model:
  config_path_mv : saved_checkpoints/single_e/config_mv.yml
  config_path_t  : saved_checkpoints/single_e/config_t.yml
  checkpoint_path: saved_checkpoints/single_e/checkpoints/epoch=77-val/loss=3.8828.ckpt

  n_steps: 25
  n_steps_to_store: 5


inf_dict:
  info: "test dataset"

  n_ensemble: 10
  save_ensemble_components: true
  entry_stop_final: 10000

  truth_path: path_to_single_e_data/test.root
  dir_flag: test_n_steps_25
